### ISSUE TITLE
global menu got zero margin

### ISSUE THREAD

**Issue by swimmingcass** [neuromorph/openbar#13]
global menubar extension: fildem fix for gnome-45

OS: ubuntu23.10

![截图 2024-02-18 15-26-14](https://github.com/neuromorph/openbar/assets/146618222/323a2ba9-afac-43be-b269-25ff4bfeb734)

**Comment by neuromorph** [comment]
Hello,
I do not have this setup where I can test it. The extension doesn't seem to be available on e.g.o after Gnome 41. It seems there is a way to manually install from Github but it also requires settings up external apps/libs. So I would need more details from you.

If they are using standard Gnome Panel Menu layout, it should work OK else there can be some issue. Quick glance shows that it maybe standard layout, though I will look more into their code but without test it is difficult. Another reason could be that they have an override for style e.g. margin which they indeed seem to have in their settings/preferences. So in that case, have you tried to adjust it from their settings?

Also, to narrow down, please report your Open Bar settings for Bar Margin and Vertical Padding.

Thanks.

**Comment by swimmingcass** [comment]
thank you for your message!

the global menu extension is "fildem", author doesn't support update anymore, but there is someone fork it and update it for gnome45 (ubuntu 23.10), you can install follow these steps:

first, install fildem deb in your system, link: https://github.com/gonzaarcr/Fildem/releases/tag/0.6.7, asserts: fildem_0.6.7_all.deb, and add it to autostart.

second, install fildem extensions in a special way, just like this:
`git clone https://github.com/Sominemo/Fildem-Gnome-45.git`
`cd Fildem-Gnome-45`
`cp -r fildemGMenu@gonza.com ~/.local/share/gnome-shell/extensions/`

fildem update for gnome45 repo: https://github.com/Sominemo/Fildem-Gnome-45

third, restart your computer.

**Comment by neuromorph** [comment]
Thanks for the instructions and also about reporting the other extension. Though the issue in them may not be same.

Also, can you please check and update about following:
>  Another reason could be that they have an override for style e.g. margin which they indeed seem to have in their settings/preferences. So in that case, have you tried to adjust it from their settings?
>Also, to narrow down, please report your Open Bar settings for Bar Margin and Vertical Padding.

**Comment by swimmingcass** [comment]
Thank you for you reply,

I have try to add vertical padding on fildem extension, but it doesn't work.

And I follow your method to setting open bar, now I have two style,
1. menu button without margin
![1](https://github.com/neuromorph/openbar/assets/146618222/ac3a3f86-59bd-4252-b782-eebb05832ac1)

2. menu button with margin
![2](https://github.com/neuromorph/openbar/assets/146618222/a20ed464-7929-47d8-97a3-2a9626d2a525)

they both pretty beauty, thanks again, very light extension, I really like it.

Best regard!

**Comment by neuromorph** [comment]
You are welcome. Yes, your styles are looking good. Thanks for the update.
A new version of Open Bar is submitted for review, you should get it soon, stay tuned!
