### ISSUE TITLE
Manaul Extension Installation Issue

### ISSUE THREAD

**Issue by in4matix** [neuromorph/openbar#15]
Hello,
I know it is better to install extensions from the website, but I like to be able to install them manually as a backup alternative. I tried on a fresh Ubuntu 22 LTS VM and this is the error it shows:

```
SyntaxError: import declarations may only appear at top level of a module

Stack trace:
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by neuromorph** [comment]
That is because the 'main' branch contains code for Gnome 45. For Gnome 42-44, you need to get the code from the 'g42-44' branch.
Due to some changes in Gnome 45, all extensions need to maintain two separate code bases.

**Comment by in4matix** [comment]
Pardon my stupidity, I should have checked that. So, I tried again, this time ensuring the correct branch, and this is what happens:
![Screenshot from 2024-03-03 09-03-11](https://github.com/neuromorph/openbar/assets/62904593/dddbaf17-e544-480a-a082-801d68c8f97c)

The settings of extension openbar@neuromorph had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by in4matix** [comment]
May I suggest creating two compressed releases, one for Gnome 42 and one for Gnome 45 ?

**Comment by neuromorph** [comment]
The error shows that you are still using code from Main branch :(
I do not keep the releases up-to-date and also `git clone` can give latest version so.

Anyway, I have now uploaded releases for both Gnome 42 and 45 as you suggested. You can use the release for Gnome 42-44.

**Comment by in4matix** [comment]
I don't understand. I double checked the branch:
![Screenshot from 2024-03-03 23-01-06](https://github.com/neuromorph/openbar/assets/62904593/f4630408-4ebc-4d76-b4d4-9d8be76d8760)
Anyway, thanks for the rekease.

**Comment by neuromorph** [comment]
That's correct branch in screenshot. If you cloned the repo, you may have to switch the branch after cloning (like: git checkout g42-44). If you downloaded zip from Github, it should say something like `openbar_g42-44.zip`

Anyway, the release should resolve the issue. So I am closing it now :+1: .
