### ISSUE TITLE
Settings available but not being applied

### ISSUE THREAD

**Issue by alyzmal** [neuromorph/openbar#19]
Version 14 of this extension installed through Nixpkgs on NixOS. Settings such as "Islands" and "Trilands" modes are available, as well as several color customization options, but do not change anything upon selection. It is entirely possible I'm missing something having installed from Nixpkgs, but I'm more confused than anything.

**Comment by neuromorph** [comment]
A similar issue was [reported here](https://www.reddit.com/r/NixOS/comments/1awq22o/does_open_bar_gnome_extension_work_for_you/). Installing from extensions gnome org web seems to have worked for them.
To be frank, I am not aware of the workings of extensions with Nixpkgs. How and when is that updated? Somehow it seems broken. I am cross-linking the reddit post with this issue in hope to get more inputs here from anyone who knows better.

Meanwhile, do try installing from the[ ego web](https://extensions.gnome.org/extension/6580/open-bar/) and let me know how it goes.

**Comment by alyzmal** [comment]
Installing them from EGO definitely worked. Must have just been a packaging quirk or outdated version or something. Thanks for all your help!
