### ISSUE TITLE
OpenBar stopped working with another extension

### ISSUE THREAD

**Issue by mkalinski** [neuromorph/openbar#20]
OpenBar version: 24 (but it's probably related to changes in 22).

The other extension: [Fullscreen Avoider](https://extensions.gnome.org/extension/4362/fullscreen-avoider/)

To reproduce:
1. Have both extensions installed and multiple monitors.
2. Switch any application on primary display to fullscreen mode.
3. The top bar is moved to another display by Fullscreen Avoider, but OpenBar styling is removed.
4. If the full screen application is removed from the primary display, the top bar is moved back and the OpenBar styling is restored.

Expected behaviour: OpenBar styling isn't removed when the top bar is moved to another display by Fullscreen Avoider. It worked like this before version 22.

I understand that it's not necessarily OpenBar's responsibility to handle compatibility with other fiddly extensions, but they did work together nicely before the recent changes in OpenBar, and it would be cool if it was possible for them to work together again.

**Comment by mkalinski** [comment]
I was able to reproduce the crash on an older OpenBar verison (by filling all monitors with fullscreen apps :wink: ) and verify that it does not crash when Fullscreen Avoider is able to move the bar to another window when the screen is being locked.

Instead there's a minor bug that makes the bar remain on the old screen (with the fullscreen app) after the screen is unlocked, and fullscreen needs to be disabled for it to show up again. This seems to only happen with OpenBar enabled, and not with just Fullscreen Avoider.

**Comment by mkalinski** [comment]
Looks like it works in my use case! :rocket:

**Comment by neuromorph** [comment]
Great!  I will close it once it gets merged in the next official update.
Feel free to add here if something crops up.

**Comment by neuromorph** [comment]
Official update is now live!
