### ISSUE TITLE
Editing bar elements background, overflow and padding on hover

### ISSUE THREAD

**Issue by MrFacundo** [neuromorph/openbar#3]
Great job!
Is there a way to config how the bar elements look on hover?
I'd like to edit their background colour and make them not overflow the bar. 
How can this be achieved?

**Comment by neuromorph** [comment]
Thank you.
The hover background color is called Highlight Color in Settings under Back Bar.
The overflow will not occur by default in the updated version. It is available in Github at the moment ('main' branch for Gnome 45).
The new version has many fixes and additions and so I would suggest you use that by manually installing from Github or wait for it to appear in Gnome extensions. I will submit for review today.
If you are already using latest version from Github but still facing this issue (or any other issue) , please provide details here (your system details, Gnome version and a screenshot/screencast of the issue).
Cheers.

**Comment by neuromorph** [comment]
Update:
New versions are up in the Extensions web now, for both Gnome <45 and Gnome 45.
Please try it and let me know if you still face any issues or if you have any questions/suggestions.

**Comment by neuromorph** [comment]
Closing as resolved in last update (v5).
