### ISSUE TITLE
Open Bar 2.0 for Gnome 42

### ISSUE THREAD

**Issue by in4matix** [neuromorph/openbar#32]
Hi there,
I would like to try out, but it is not available in Gnome 42-44 branch?

**Comment by neuromorph** [comment]
It is hard to keep both in sync since it is still not finalized. I will push the 42 version in the g42-44 branch in a few days.

**Comment by in4matix** [comment]
Thanks dude! You Rock!

**Comment by in4matix** [comment]
Oh BTW, I have a Fedora 40 station, but still prefer my Ubuntu 22 LTS daily driver.

**Comment by neuromorph** [comment]
>  I have a Fedora 40 station

OK cool, you can try out on that in the meanwhile.

**Comment by in4matix** [comment]
Seems to be working fine.
![Screenshot from 2024-05-17 14-20-17](https://github.com/neuromorph/openbar/assets/62904593/3ae08f73-ca4f-4084-8970-0d58fe83024e)

**Comment by neuromorph** [comment]
Hello,

Open Bar 2.0 is now available for Gnome 42 in the 'g42-44' branch.
It is up to date with OpenBar2.0 branch.

Let me know how it goes.

**Comment by in4matix** [comment]
Hey,
I must admit that I haven't tinkered around with all the settings. I just used auto-theme and changed a couple of settings to make the theme more translucent and changed some accent colors to get it to the way I like it. Works great on Ubuntu 22.

**Comment by neuromorph** [comment]
Hello,

There were many more fixes / updates added to G45+ in last couple weeks and I have now ported them all to 'g42-44' branch.
Please pull / download latest commit to get them.

Thanks.

**Comment by in4matix** [comment]
@neuromorph , thank you for keeping the g42-44 branch updated. I have played around with G46 on various distro's and there is absolutely no viable reason for me to change from Ubuntu 22 LTS as my daily workhorse. I might change to Ubuntu 24 LTS in a year or two.

**Comment by neuromorph** [comment]
OpenBar 2.0 is now up to date for Gnome 42 and live on Extensions web so closing the issue.
