### ISSUE TITLE
TypeError: dot.add_style_class_name is not a function

### ISSUE THREAD

**Issue by Blade04208** [neuromorph/openbar#39]
upon installing the extension either manually or with gnome-extension-manager, it will throw
`TypeError: dot.add_style_class_name is not a function` and disable the extension.

system details via gnome settings below
# System Details Report
---

## Report details
- **Date generated:**                              2024-06-15 12:41:09

## Hardware Information:
- **Hardware Model:**                              SAMSUNG ELECTRONICS CO., LTD. 750XFG
- **Memory:**                                      8.0 GiB
- **Processor:**                                   13th Gen Intel® Core™ i5-1335U × 12
- **Graphics:**                                    Intel® Graphics (RPL-U)
- **Disk Capacity:**                               (null)

## Software Information:
- **Firmware Version:**                            P07CFL.028.240221.HQ
- **OS Name:**                                     EndeavourOS
- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.9.4-arch1-1

**Comment by neuromorph** [comment]
Hello,

It refers to the little Workspace Dots indicator (Activities Button) on the top let corner in the panel:
![Screenshot from 2024-06-15 18-04-59](https://github.com/neuromorph/openbar/assets/4656768/60cf0be5-3d4f-478e-a0fa-19a3c3d4927f)

Do you have this in your setup, or is there any custom config that changed it? I have not tried with  EndeavourOS.

If it is not used in EndeavourOS then I will add a check to bypass it. However, if it is there then we need to investigate why it is complaining (likely the layout of Workspace dots is changed). It could also be some extension that changes the dots to something else.

BTW, besides this, I would suggest to try a manual install from the GitHub 'openbar2.0' branch. It is the new version about to be uploaded. If a fix is required for the above issue, I will add it to this version before uploading.

Thank you for reporting!

**Comment by Blade04208** [comment]
yes, i do have it, and im pretty sure 'Add Custom Text to Workspace Indicators' may have screwed it. Disabling that and re-installing Open Bar makes Open Bar work. However, re-enabling Add Custom Text to Workspace Indicators seems to make Open Bar work fine.

**Comment by neuromorph** [comment]
> Disabling that and re-installing Open Bar makes Open Bar work. However, re-enabling Add Custom Text to Workspace Indicators seems to make Open Bar work fine.

Unfortunately, it will most likely break again when you update a setting or when screen lock/unlock etc.
I have added a compatibility fix to 'openbar2.0' branch. I suggest you download that and install manually and logout/login to reload Gnome.

Let me know how it goes.

Thanks!

**Comment by neuromorph** [comment]
The fix for this is live now in the published version on e.g.o.
Closing here.
