### ISSUE TITLE
Added openbar to nixpkgs

### ISSUE THREAD

**Issue by heywoodlh** [neuromorph/openbar#40]
Relevant PR is here: https://github.com/NixOS/nixpkgs/pull/320626

Please let me know if this is an issue! And thank you for the great extension :)

**Comment by neuromorph** [comment]
Thank you for adding to nixpkgs!

- It's pending some checks / review it seems?
- Were you able to provide write access to the Openbar extension's install dir? else it may encounter the permission denied issue.
- How do updates work? The new version (currently under Gnome review) will soon be merged into 'main' branch. Will it get pulled from GitHub or does it need to be manually packaged again?

**Comment by jtojnar** [comment]
It cannot work without #38 being resolved.

Also we have an [semi-automated system](https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/gnome/extensions/README.md) that creates packages for all GNOME Shell extensions on e.g.o, so unless some special consideration is needed, manual package should not be necessary.
