### ISSUE TITLE
Openbar breaks with the new update

### ISSUE THREAD

**Issue by cortegaunam** [neuromorph/openbar#44]
Openbar was working correctly and now that it has been updated it no longer starts correctly and I get the following message:
 
![Captura desde 2024-06-21 10-22-29](https://github.com/neuromorph/openbar/assets/44278917/13cdf8b1-04d6-410d-9001-beb7237319f6)

**Comment by neuromorph** [comment]
There is a bug in stylesheet code, the next update will include the fix.
For now, you can get the fix by running following command. It will replace local `stylesheets.js` with updated version from GitHub.

`cd ~/.local/share/gnome-shell/extensions/openbar@neuromorph/; curl -LJO https://raw.githubusercontent.com/neuromorph/openbar/main/stylesheets.js; cd`

After running this, you will need to logout and login again for the changes to take effect.

Let me know how it goes.

Thanks!

**Comment by cortegaunam** [comment]
Thanks, it's working again.
