### ISSUE TITLE
Extension breaks on login

### ISSUE THREAD

**Issue by Rotvoid** [neuromorph/openbar#45]
Every time I log into my laptop the Extension goes inactive. Pop OS with Gnome 42.9. The Extension window tells me "obj is undefined". 
If I change any color setting the extension goes back to working as normal, but still shows the error in the extension window and the extension itself as inactive.
The only other extension affecting the top bar I have active is Aylur's Widgets. The error only happens since I updated Open Bar this morning.

**Comment by neuromorph** [comment]
Hello,

What version of Open Bar are you on?  I guess v31, but please check and confirm.

Please run the following command in a terminal and then Enable the extension. If the error is preventing the extension from enabling then just remove and install the extension again while the command is running. If there is no error during enable then keep the command running and try disabling the extension. At some point the same error will show up in the terminal but it will also have a trace log. Please share that here so we can debug the issue.

`SHELL_DEBUG=all journalctl /usr/bin/{gjs,gnome-shell} -fo cat`

Thank you for reporting!

**Comment by Rotvoid** [comment]
v31. Ran the command, Error popped up when i reinstalled and it immediately disabled itself. Kept working as normal though. This is what I got:

JS ERROR: Extension openbar@neuromorph: TypeError: obj is undefined
connect@/home/user/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:49:13
applyMenuStyles@/home/user/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:415:47
enable@/home/user/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:1139:14
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:183:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:384:26
_onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:278:35
Async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:132:41

**Comment by neuromorph** [comment]
Thanks for the log. This error is a bit weird and unexpected. 
However, the Gnome 42-44 version was lagging behind and few fixes have been added in the 45+ version, so I have ported all the latest fixes into the 'g42-44' branch on GitHub. Hopefully, that will also fix this issue. If not, there maybe something specific to your Top Bar setup. I have tested this update from GitHub in a VM with Ubuntu 22.04 (Gnome 42) and also with Aylur's Widgets extension and it worked OK.
You will need to manually install the update by downloading zip (or git cloning) the branch 'g42-44'.
After installing you need to logout and login again for the changes to take effect.

Please try it out and let me know how that goes. If all's well then I will include it in the next version soon.

**Comment by neuromorph** [comment]
Oh yeh, the GitHub update can get overwritten on login if the version on ego web is newer. After installing from GitHub branch, in the file 'metadata.json' , change the version to 31 so that it won't get overwritten  with update.

**Comment by Rotvoid** [comment]
makes sense. Did that, still working the way I'd expect it to. Not sure if the version I had just decided to fix itself after who knows hoq many reinstalls or if having the g42-44 branch for 5 seconds did that somehow but I'll take it.

**Comment by neuromorph** [comment]
The up to date version for Gnome 42-44 is now live on Extensions web, so closing this issue.
