### ISSUE TITLE
Extension broken on fedora gnome 46

### ISSUE THREAD

**Issue by error23** [neuromorph/openbar#46]
Cannot parse CSS for some raison since last update 

All it's written in French is just the classical boilerplate to say hey extension is not working, you should consider disabling it until it starts working correctly again.

Then I have this Gio.IOErrorEnum exception that basically says me cannot parse stylesheet.css with errorcode 15

I tried to google it a bit but didn't found what does it means

### Screen
![Sans titre](https://github.com/neuromorph/openbar/assets/5151571/a783dd66-83c4-4dc1-af5c-586bf99838c3)

### Settings
```
[/]
accent-color=['0', '1', '0.8599998950958252']
accent-override=true
autofg-bar=false
autofg-menu=false
autotheme='Color'
autotheme-refresh=false
balpha=0.0
bartype='Mainland'
bcolor=['0.6470588445663452', '0.11372549086809158', '0.1764705926179886']
bg-change=true
bgalpha=1.0
bgalpha-wmax=0.90000000000000002
bgalpha2=0.0
bgcolor=['0', '0', '0']
bgcolor-wmax=['0.09411764705882353', '0.10980392156862745', '0.17254901960784313']
bgcolor2=['0', '0.05098035931587219', '0.11372549086809158']
bgpalette=false
bguri='file:///home/error23/.local/share/backgrounds/2023-05-10-20-45-08-wallpaper-56.png'
border-wmax=false
bordertype='solid'
boxalpha=1.0
boxcolor=['0.8784313797950745', '0.10588235408067703', '0.1411764770746231']
bradius=0.0
bwidth=0.0
candy1=['0.15', '0.62', '0.79']
candy2=['0.313', '0.176', '0.945']
candy3=['0.93', '0.30', '0.54']
candy4=['0.11', '0.44', '0.85']
candy5=['0.18', '0.76', '0.49']
candy6=['0.51', '0.24', '0.61']
candy7=['1', '0.47', '0']
candy8=['0.9', '0.65', '0.04']
candyalpha=0.90000000000000002
candybar=false
cust-margin-wmax=false
default-font='Sans 12'
extend-menu-shell=true
fgalpha=1.0
fgcolor=['0.01627776212990284', '0.592510998249054', '0.9766666889190674']
font='Roboto Medium 12'
gradient=true
gradient-direction='horizontal'
halpha=1.0
handle-border=3.0
hcolor=['0.007843131199479103', '0.11372548341751099', '0.20392157137393951']
heffect=false
height=32.0
hpad=0.0
import-export=true
isalpha=1.0
iscolor=['0.023529411764705882', '0.0392156862745098', '0.13725490196078433']
margin=13.0
margin-wmax=2.0
mbalpha=0.75
mbcolor=['0', '0.607083261013031', '0.7833333611488342']
mbg-gradient=false
mbgalpha=0.75
mbgcolor=['0', '0.05098035931587219', '0.11372549086809158']
menu-radius=16.0
menustyle=true
mfgalpha=1.0
mfgcolor=['0', '0.940000057220459', '1']
mhalpha=0.25
mhcolor=['0', '0.7254900932312012', '1']
monitors='all'
msalpha=0.65000000000000002
mscolor=['0', '0.7254900932312012', '1']
mshalpha=0.14000000000000001
mshcolor=['0', '1', '0.940000057220459']
neon=false
neon-wmax=false
notif-radius=16.0
palette1=['192', '202', '231']
palette10=['56', '89', '66']
palette11=['82', '52', '76']
palette12=['28', '49', '52']
palette2=['31', '78', '195']
palette3=['69', '177', '225']
palette4=['24', '41', '122']
palette5=['5', '7', '27']
palette6=['14', '24', '77']
palette7=['148', '132', '185']
palette8=['222', '176', '62']
palette9=['193', '76', '90']
pause-reload=false
position='Top'
prominent1=['190', '197', '224']
prominent2=['6', '10', '35']
prominent3=['31', '78', '195']
prominent4=['69', '177', '225']
prominent5=['24', '41', '122']
prominent6=['56', '89', '66']
qtoggle-radius=50.0
radius-bottomleft=false
radius-bottomright=false
radius-topleft=false
radius-topright=false
reloadstyle=false
removestyle=false
set-notifications=true
set-overview=true
shadow=false
shalpha=0.20000000000000001
shcolor=['0.8', '0.8392156862745098', '0.9058823529411765']
slider-height=4.0
smbgalpha=0.94999999999999996
smbgcolor=['0.007843131199479103', '0.11372548341751099', '0.20392157137393951']
smbgoverride=true
trigger-autotheme=true
trigger-reload=true
variation='Default'
vpad=0.0
width-bottom=false
width-left=false
width-right=false
width-top=false
wmaxbar=false
```

**Comment by 1amnotmad** [comment]
I have this issue as well. I am on Fedora Atomic Silverblue with Gnome 46.

**Comment by neuromorph** [comment]
Hello @error23 and @1amnotmad ,

There is a bug in stylesheet code, the next update will include the fix.
For now, you can get the fix by running following command. It will replace local stylesheets.js with updated version from GitHub.

cd ~/.local/share/gnome-shell/extensions/openbar@neuromorph/; curl -LJO https://raw.githubusercontent.com/neuromorph/openbar/main/stylesheets.js; cd

After running this, you will need to logout and login again for the changes to take effect.

Note: You only need the above for this issue. But if you don't mind then you can download the entire code or git clone from the 'main' branch. There is at least one more fix there for another issue and I will be adding there if anything else pops up today and then upload it to Gnome Extensions for review and release.

Let me know how it goes.

Thanks!

**Comment by vrecek** [comment]
Hey @neuromorph 

I have the same issue, same as @error23 and @1amnotmad that's why im here. But i think there is an error in your answer. Instead of CURLing stylesheets.js, it should be stylesheet.css. Replacing .css file resolves the issue, but .js does not.

**Comment by neuromorph** [comment]
Hello @vrecek 

Thanks for writing!
The stylesheet css is dynamic and will be regenerated so without the updated 'js' you will face the same issue again. The key is to make sure you logout and login after replacing the 'js' file. If you did that and still facing the issue then most likely the stale faulty stylesheet prevented the extension from enabling. In that case, yes, you can replace Both files. 

There is another simpler way as well - If you turn on 'Auto FG Color' under 'Bar Foreground' tab then it will fix the stylesheet and the error will go away. So css will not be problem anymore. However, you do still need to replace the 'js' so that the error does not occur when you disable 'Auto FG Color'.

**Comment by vrecek** [comment]
@neuromorph 

Yeah i replaced the javascript file first, and it did not work even after couple of logouts, so I decided to replace the css as well.

Thanks for answer

Arch, GNOME 46.2 on Wayland, in case someone's wondering

**Comment by error23** [comment]
Thanks a lot @neuromorph 

I cloned master branch just to have the latest version reimported my settings and it's fixed now :)

**Comment by 1amnotmad** [comment]
Thank  you @neuromorph ! I grabbed main, and I'm back in business.  Coffee incoming! Thanks.

**Comment by neuromorph** [comment]
Thank you guys for informing that the fix worked! It will be part of the next update coming soon.

@1amnotmad , Thanks much for the coffee! Truly appreciate your support for the project.
