### ISSUE TITLE
[BUG]: Auto-theming does not detect changing wallpaper via gsettings command

### ISSUE THREAD

**Issue by mkalinski** [neuromorph/openbar#48]
**Describe the bug**
Because I have a lot of wallpapers catalogued in separate folders, I don't use the settings app to switch wallpapers. Instead, I navigate to a chosen folder and run a simple script to change the wallpaper.

```sh
#!/bin/sh
image_path="${1:?Missing argument 1: path to image}"
abs_image_path="$(realpath "$image_path")" || exit

setpicuri() {
	gsettings set "$1" "$2" "file://$abs_image_path" || exit
}

setpicuri org.gnome.desktop.background picture-uri
setpicuri org.gnome.desktop.background picture-uri-dark
setpicuri org.gnome.desktop.screensaver picture-uri
```

This triggers a "normal" change of wallpaper by Gnome (with cross-fade).

This used to work trigger automatic palette change in OpenBar, but somewhere on the way to 2.0 release it stopped working. Now OpenBar only reacts to wallpaper changes triggered by the Gnome Settings app.

**To Reproduce**
1. Execute the `gsettings` commands from the script above with URI to any image file.
2. Wallpaper change is triggered in Gnome.
3. Auto-theming palette change is not triggered in OpenBar.

**Relevant  Specs:**
 - Open Bar version: 35
 - Gnome version: 46
 - OS/Distribution: Fedora 40

**Comment by mkalinski** [comment]
Thanks! Looks like it works.

**Comment by itsfirestorm** [comment]
This issue is persistent in the most recent version (OpenBar 45, using Gnome 47 on Arch Linux latest kernel).

I have a very similar script, but I use wofi to select a wallpaper instead of specifying it somewhere or setting it manually from Gnome Settings.
```
# Set some variables
wall_dir="${HOME}/.config/wallpapers/"

# Select a picture with wofi
wall_selection=$(find "${wall_dir}" -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" -o -iname "*.gif" \) -exec basename {} \; | sort | wofi -dmenu -i -p "Select a wallpaper")

# Checks if the wallpaper has been set, if it wasn't set, exits the program without doing changes.
[[ -n "$wall_selection" ]] || exit 1

# Set colorschemes with pywal
wal -i ${wall_dir}/${wall_selection}
# Apply wallpaper.
gsettings set org.gnome.desktop.background picture-uri "${wall_dir}/${wall_selection}"
gsettings set org.gnome.desktop.background picture-uri-dark "${wall_dir}/${wall_selection}"
```
As the issue above, this triggers a normal wallpaper change and pywal applies the color scheme to my terminal. However, OpenBar does not detect the change and remains with the same colorscheme every change.
