### ISSUE TITLE
[BUG]: Inactive button incorrectly themed in shell screenshot overlay

### ISSUE THREAD

**Issue by mkalinski** [neuromorph/openbar#49]
**Describe the bug**
Pressing "Print Screen" in Gnome launches the screenshot-taking overlay. It has three big button to select the scope of the screenshot: selection, screen, window. It also has two modes: taking screenshot or screencast.

In the screencast mode, the "window" button is disabled, as recording a single window seems not to be supported (at least on my system). In the default Gnome shell theme, the button is greyed out.

However, when "Apply All Styles to Shell allover" is enabled in OpenBar, the button looks the same as the other buttons, even though it's disabled and can't be clicked.

**To Reproduce**
1. Enable "Apply All Styles to Shell allover" in Gnome Shell section of OpenBar configuration.
2. Press "Print Screen" to launch Gnome screenshot overlay.
3. Click on the webcam button to enable screencast mode.
4. "Window" button is disabled, but it's not visible with OpenBar styling applied.

**Relevant  Specs:**
 - Open Bar version: 35
 - Gnome version: 46
 - OS/Distribution: Fedora 40

**Screenshots**
I would like to provide some, but I don't know how to screenshot the screenshotter app itself. :grin:

**Comment by neuromorph** [comment]
Thank you for reporting!

A fix is added to `main` . Let me know how it goes.

**Comment by mkalinski** [comment]
Looks fixed, thanks.

**Comment by neuromorph** [comment]
New version of Open Bar with the fix is live on Gnome extensions, closing here.
