### ISSUE TITLE
[BUG]: Bar in bottom position does not sync well with Bar Margin

### ISSUE THREAD

**Issue by neuromorph** [neuromorph/openbar#51]
**Describe the bug**
Bar in bottom position does not sync well with Bar Margin and WMax Bar margin. Bar can get cut at bottom or have unwanted gap.

**To Reproduce**
- Keep bar in Bottom position
- Turn On WMax Bar
- Change Bar margin while a window is maximized
- Change WMax margin when 'Custom Bar Margin' is On and a window is maximized

**Relevant  Specs:**
 - Open Bar version: `main` branch
 - Gnome version: 45+

**Comment by neuromorph** [comment]
Fix has been added in this [commit](https://github.com/neuromorph/openbar/commit/fa3a03ec25e9755e78be513a4746d775045a1af4) to be included in next update.

**Comment by neuromorph** [comment]
@balintbarna FYI

**Comment by balintbarna** [comment]
awesome, looking forward :)

**Comment by neuromorph** [comment]
Please feel free to report any other issues that you referred to in the `nixfix` branch that were unrelated to it.

**Comment by neuromorph** [comment]
Update:
The `nixfix` branch is now merged into `main` along with all the other fixes. So please install from `main` branch for further tests.

**Comment by neuromorph** [comment]
New version of Open Bar with the fix is live on Gnome extensions, closing here.
