### ISSUE TITLE
Workspace Indicator from Screenshots

### ISSUE THREAD

**Issue by redscorpse** [neuromorph/openbar#55]
I would like to know how can i get the same workspace indicator as the one that is shown on screenshots:
![ ](https://github.com/neuromorph/openbar/assets/73442486/1345b379-a7c6-49f0-a1e8-be9373a4e8e2)

**Comment by neuromorph** [comment]
That is the default Gnome workspace dots indicator. It was introduced in Gnome 45, iirc.
Open Bar adds the shape/color/border styles to it.

If you are on Gnome 45+, you will have it, unless you installed an extension that hides or replaces it.

**Comment by redscorpse** [comment]
Oh tanks for answering. Currently I am on Debian 12, using GNOME 43.9 so that's why I don't have it yet.
