### ISSUE TITLE
[BUG]: TypeError: btns[k].child is null

### ISSUE THREAD

**Issue by yamid-rc** [neuromorph/openbar#61]
**Describe the bug**
op Bar / Top Panel , Menus , Dash / Dock , Gnome Shell , Gtk Apps theming. Open the bar and let the colors 🍹 flow.

**To Reproduce**
 Only the extension crash by self. So when my computer pass to screensaver and return to desktop, the extension died.

**Relevant  Specs:**
 - Open Bar version: 37
 - Gnome version: 46
 - OS/Distribution: Debian Experimental (is Debian 12)
 - Other installed extensions if interference is expected [Optional]: 

**Screenshots**
![image](https://github.com/user-attachments/assets/d7e2ff6e-7ed4-474b-81ac-07bc8ba1491f)

![image](https://github.com/user-attachments/assets/8a3bdf50-95ed-4335-9d71-6414d31a1357)

**Error Stack Trace**

**Comment by neuromorph** [comment]
Hello,

Thank you for reporting!
I have added a fix in GitHub `main` branch. You can install from there or you can also just run following command in terminal to get the fix.

`cd ~/.local/share/gnome-shell/extensions/openbar@neuromorph/; curl -LJO https://raw.githubusercontent.com/neuromorph/openbar/main/extension.js; cd`

After running this, you will need to logout and login again for the changes to take effect.

Let me know how it goes.

Thanks.

**Comment by fadhly-permata** [comment]
> Hello,
> 
> Thank you for reporting! I have added a fix in GitHub `main` branch. You can install from there or you can also just run following command in terminal to get the fix.
> 
> `cd ~/.local/share/gnome-shell/extensions/openbar@neuromorph/; curl -LJO https://raw.githubusercontent.com/neuromorph/openbar/main/extension.js; cd`
> 
> After running this, you will need to logout and login again for the changes to take effect.
> 
> Let me know how it goes.
> 
> Thanks.

Thanks for the quick update.. the error has been gone, and running well.. Thanks a lot bro..

**Comment by neuromorph** [comment]
A new version v38 with the fix has been released, closing this.
