### ISSUE TITLE
[Feature Request] Transparent buttons when WindowMax

### ISSUE THREAD

**Issue by saligari** [neuromorph/openbar#64]
When the window is maximized it is usually to give your focus to the maximized window, it would be a good feature to minimize distractions then. 

What happens now when windows are maximized: 
![image](https://github.com/user-attachments/assets/ac3c8113-1106-4566-b7ec-1c9b80228200)

Desired outcome would be the default gnome top bar: 
![image](https://github.com/user-attachments/assets/cd8a2f41-69e5-454a-a3fa-7228f61d6a5f)

Thank you!!

**Comment by neuromorph** [comment]
This is in progress. There will be an option under WindowMax Bar with a choice to either keep the buttons colors or not.
I will update here when it is ready to test.

**Comment by neuromorph** [comment]
This is now available in `main` branch i.e. WindowMax Bar has a choice to either keep the buttons colors or not.
You will need to install manually by downloading from `main` branch to try it out.

Thanks.

**Comment by saligari** [comment]
Thanks!

Minor issue: When you change virtual desktops from the overview, the buttons retain their coloring. Even if I don't change desktop and just press super key and go back to the same desktop, with a max window and colorless buttons, their coloring returns.

**Comment by neuromorph** [comment]
Oops, it was a bug. Good catch!
It is fixed in the `main` branch now. Only update is in `extension.js`.

Thank you for the feedback!

**Comment by neuromorph** [comment]
It is now released on Gnome extensions web in v39.
Closing here.
