### ISSUE TITLE
[BUG]: Auto Highlight color not being triggered

### ISSUE THREAD

**Issue by DonElvillano** [neuromorph/openbar#75]
**Description**
When the auto highlight color is active and changing the background the color still the same as it previous color and only can be changed manually 

**To Reproduce**
1.Set the highlight color manually for any color
2. Change the background to any other picture that does not contain the previously set highlight color to make sure the auto theming will be triggered
3. Check the auto highlight option which will stay as it was before switching the background

**Relevant  Specs:**
 - Open Bar version: 41
 - Gnome version: 47
 - OS/Distribution: Arch Linux

**Screenshots**
1st Screenshot: Notice the auto theming colors
2nd Screenshot: The highlight color is manually set to dark blue
3rd Screenshot: Change to another background to get new color palette
4th Screenshot: The highlight color auto theming should be triggered here but notice that the color is still same as it was set before in the 1st screenshot

![Screenshot From 2024-09-21 19-26-01](https://github.com/user-attachments/assets/c971e556-5fcb-4e15-a229-7a4b7a7af3ee)
![Screenshot From 2024-09-21 19-26-17](https://github.com/user-attachments/assets/174cc40a-ae62-4736-9e0f-0ce6bed8a21a)
![Screenshot From 2024-09-21 19-27-08](https://github.com/user-attachments/assets/5bec43cc-2406-47b3-a5e5-ec4da8f0c5d8)
![Screenshot From 2024-09-21 19-27-17](https://github.com/user-attachments/assets/13544f2d-dfd0-4f08-9edb-9375a32ce274)

**Video**
Here is a video I hope it will make everything clear.
[Screencast From 2024-09-21 19-39-53.webm](https://github.com/user-attachments/assets/d32a5b1c-3b7f-4a44-af60-a605e53e18f5)

**Comment by neuromorph** [comment]
Hello,

> When the auto highlight color is active and changing the background the color still the same as it previous color and only can be changed manually

Yes. There are multiple things at play so let me explain how it works and then we can look into further updates.

Auto Highlight Color:
In the beginning, with Autotheming,  we were auto-selecting a colorful color from the generated palette as highlight color. However, that did not fair too well as it does not align well with expectations of most users and sometimes it would end up having too much contrast. The new version tries to keep the highlight color as grayscale similar to default Gnome or popular themes but the shade of gray is computed automatically based on the background color for the bar/menu/submenu or accent (active). This is what will happen if you turn On the "Auto Highlight Color" option. In this case, the manually selected highlight color will be ignored.
For people who do want to use whatever color they fancy, the manual color option is still present, they just need to turn Off the "Auto Highlight" option.

The above feature always works like that and not tied to Autotheming. So it will work the same when you change the background also. But I get your point, you are expecting the manual highlight color should change to something from the background color palette when the background is changed and Autotheming-refresh is On.
This part is missing now, I can look into it to auto-select a color from the palette when auto-theming applied or background is changed. 

However, as explained above Autotheming and Auto-Highlight-Color are different options. Auto-Highlight will always apply a suitable grayscale color as per the BG color. On the other hand, if you wish to use manual color or a color from the palette as selected by autotheming (once that part is implemented), you would need to turn Off Auto-Highlight.

Thanks for reporting!
Let me know if this is clear and if the proposed addition is what you expected.
