### ISSUE TITLE
Auto updating of color scheme when changing wallpaper changes icon pack in Gnome Tweaks

### ISSUE THREAD

**Issue by jkblank** [neuromorph/openbar#82]
Every time I change my wallpaper, and the colours are automatically updated and applies through the whole system, my Icon Pack also changes. 
Running Gnome 46 on X11 
Linux 6.6.54-2-MANJARO

**Comment by neuromorph** [comment]
Hello,

Icon pack is changed only for Yaru themes, if enabled. Are you using Yaru themes? If not, go to Open Bar settings > Gtk / Flatpak Apps and turn off the option called "Set Yaru Theme".

If you do want to use Yaru Gtk themes but do not want to use Yaru Icons, then that option would need to be split into two, Gtk and Icon to toggle individually. That is not available currently. Turning off the above switch should fix it for the most part anyway. 

Let me know how that goes and what Theme, Icon pack you are using, and also OpenBar version.

Thanks for reporting!
