### ISSUE TITLE
[BUG]: Top bar is not rounding properly

### ISSUE THREAD

**Issue by kimjongbing** [neuromorph/openbar#87]
**Describe the bug**
When installing the extension, the top bar has square corners peeking out from them. Whatever setting I adjust these square corners do not go away. I am assuming this is not expected behavior. 

**To Reproduce**
Install the extension.

**Relevant  Specs:**
 - Open Bar version: : 41
 - Gnome version: 47.1
 - OS/Distribution: NixOS 24.11.20241111.dc460ec (Vicuna) x86_64
 - Other installed extensions if interference is expected [Optional]: 
  20   │       gnomeExtensions.clipboard-indicator
  21   │       gnomeExtensions.blur-my-shell
  22   │       gnomeExtensions.appindicator
  23   │       gnomeExtensions.solaar-extension
  24   │       gnomeExtensions.dash-to-dock
  25   │       gnomeExtensions.bluetooth-battery-meter
  26   │       gnomeExtensions.hide-cursor
  27   │       gnomeExtensions.kimpanel
  28   │       gnomeExtensions.tiling-shell
  29   │       gnomeExtensions.gsconnect
  30   │       gnomeExtensions.quick-settings-audio-panel
  31   │       gnomeExtensions.open-bar
  32   │       gnomeExtensions.systemd-manager

**Screenshots**
![image](https://github.com/user-attachments/assets/4353179d-2cfc-4e09-9b3b-c892cc072dd5)
![image](https://github.com/user-attachments/assets/2a1a3dd1-f724-40b7-9cf8-19fac77c014e)
![image](https://github.com/user-attachments/assets/b1b9b1d9-81b0-4aa6-a985-7fa6485b8f73)
![image](https://github.com/user-attachments/assets/99ca3209-5e0f-45bc-a787-bb08d00b4459)

**Comment by neuromorph** [comment]
Hello,

This is most likely an artifact of blurring. You probably have Panel blurring On in Blur My Shell. I had added a PR there to make it work for floating bar however it will only work for Static blur. Dynamic blur in Gnome has inherent limitation that does not allow rounded corners. 

Solution: 
If you are using latest version (more or less) of Blur My Shell, then select Static blur for Panel in their settings.
Else, disable Panel blur in BMS.

Thanks for writing!

**Comment by kimjongbing** [comment]
> Hello,
> 
> This is most likely an artifact of blurring. You probably have Panel blurring On in Blur My Shell. I had added a PR there to make it work for floating bar however it will only work for Static blur. Dynamic blur in Gnome has inherent limitation that does not allow rounded corners.
> 
> Solution: If you are using latest version (more or less) of Blur My Shell, then select Static blur for Panel in their settings. Else, disable Panel blur in BMS.
> 
> Thanks for writing!

Ok thank you! :D
