### ISSUE TITLE
[BUG]: OpenBar is "always working" even on 3D fullscreen or windowed-fullscreen applications (mainly gaming) 

### ISSUE THREAD

**Issue by RalL64** [neuromorph/openbar#89]
**Describe the bug**
When using gamescope or playing CS2 (CS2 is where i find the bug to be more easy to reproduce on my end) OpenBar just works but not as intended since by example, when i put my cursor on where gnome taskbar is, the trays just opens (when i say tray i mean, when i click the hours+calendar region even o a fullscreen gaming or when using gamescope, the calendar/hour tray will open and happens the same for the other regions on fullscreen). But, when i disable OpenBar everything work as intended, nothing opens on fullscreen, just normal. And with gamescope is even more buggier. 

**To Reproduce**

- Open CS2 and play it on windowed-fullscreen
- Open CS2 with gamescope 
- Open CS2 with gamescope with this args: gamescope -w 1280 -h 960 -S stretch -e -f -r 59 --force-grab-cursor --immediate-flips --  %command 
- Open any other game with gamescope 

**Relevant  Specs:**
 - Open Bar version: 41
 - Gnome version: 47
 - OS/Distribution: Arch Linux
 - Other installed extensions if interference is expected [Optional]: (Maybe and only maybe, Arc Menu, Mpris label, Vitals, Wheater O'Clock)

**Screenshots**
Screenshots attached
![Screenshot From 2024-11-27 08-32-01](https://github.com/user-attachments/assets/881ec3e3-dc92-4c1d-aff3-cfd8634c45ab)
![Screenshot From 2024-11-27 08-32-10](https://github.com/user-attachments/assets/5ea9f10d-3d0d-4383-88ba-2a2868b93a19)

**Comment by neuromorph** [comment]
Hello,

Some of these issues were fixed in GitHub a while back except for an upstream related issue about Crash-on-lock faced by some of the users. In pursuit of the crash issue , other things also missed on release and now I am too busy to review and release new version. It is on my ToDo.
Meanwhile, you can get the latest version from GitHub `main` branch and install it manually. It should fix this bug for you.

Thanks for reporting!

**Comment by RalL64** [comment]
> Hello,
> 
> Some of these issues were fixed in GitHub a while back except for an upstream related issue about Crash-on-lock faced by some of the users. In pursuit of the crash issue , other things also missed on release and now I am too busy to review and release new version. It is on my ToDo. Meanwhile, you can get the latest version from GitHub `main` branch and install it manually. It should fix this bug for you.
> 
> Thanks for reporting!

Thanks mate, i will do that!
